### ISSUE TITLE
Data question

### ISSUE THREAD

**Issue by Nina1031** [avakanski/Attention-Enriched-Deep-Learning-Model-for-Breast-Tumor-Segmentation#3]
hello, I wanna try your algorithm for breast tumor segmentation. So I downloaded the code. But it needs 
# Directory with salient masks, images, and ground truths
path_sals = "../Data/saliency_maps/"
path_imgs = "../Data/images/"
path_masks = "../Data/masks/"

I wonder where the data is. Should I replace them with my own figures?

**Comment by avakanski** [comment]
Yes, the idea is that the users will provide their own data. If you are new to this area and you don't have breast ultrasound images, you can find open datasets on the web (let me know if you need any help with that).
Please note that I didn't post the codes for calculating the saliency maps of images. This is because I didn't develop this approach. However, if you need the codes, you can contact the author of the approach Dr. Fei Xu (fei.xu at aggiemail.usu.edu), and I believe that Dr. Xu would be willing to share the codes.

**Comment by Nina1031** [comment]
Thanks for your patient reply.
